#!/bin/sh
if [ -z $p ]; then
	p=python3
fi
if [ -e dest ] && [ -z "${skip_src}" ]; then
	rm -r dest
fi
if [ -z "${OAPATH}" ]; then
	export OAPATH=../../oaas
fi
header=550:400:12:ffFFff $p ../../oaas3 dest a.swf
