
const asciinul=0x0
const asciitab=0x9
const asciinewline=0xa
const asciispace=0x20            #' '
const asciidquote=0x22           ;#"
const asciipercent=0x25          ;#%
const asciiasterisk=0x2a         ;#*
const asciiand=0x26              ;#&
const asciiparenthesisleft=0x28  ;#(
const asciiparenthesisright=0x29 #)
const asciiplus=0x2b             ;#+
const asciicomma=0x2c            #,
const asciihyphen=0x2d           ;#-
const asciidot=0x2e              #.
const asciislash=0x2f            ;#/
const asciizero=0x30             #0
const asciione=0x31              #1
const asciisemicolon=0x3b        #;
const asciileft=0x3c             ;#<
const asciiright=0x3e            ;#>
const asciisquareleft=0x5b       #[
const asciibs=0x5c               #\
const asciisquareright=0x5d      #]
const asciicirc=0x5e             ;#^
const asciic=0x63                #c
const asciicurlyleft=0x7b        #{
const asciior=0x7c               ;#|
const asciicurlyright=0x7d       #}
const asciinot=0x7e              #~
